export const Tool_LINE = 'line';
export const Tool_RECTANGLE = 'rectangle';
export const Tool_CIRCLE = 'circle';
export const Tool_TRIANGLE = 'triangle';
export const Tool_PAINT_BUCKET = 'paint-bucket';
export const Tool_PENCIL = 'pencil';
export const Tool_BRUSH = 'brush';
export const Tool_ERASER = 'eraser';
//# sourceMappingURL=tool.class.js.map